import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent } from "@/components/ui/card";
import { Loader2, Sparkles } from "lucide-react";
import QuizDisplay from "./QuizDisplay";

interface Question {
  question: string;
  options: string[];
  correct_answer: number;
  explanation: string;
}

interface QuizData {
  title: string;
  summary: string;
  questions: Question[];
  key_entities: string[];
  related_topics: string[];
}

export default function GenerateQuizTab() {
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [quiz, setQuiz] = useState<QuizData | null>(null);

  const validateUrl = (url: string): boolean => {
    try {
      const urlObj = new URL(url);
      return urlObj.hostname === "en.wikipedia.org";
    } catch {
      return false;
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setQuiz(null);

    if (!url.trim()) {
      setError("Please enter a Wikipedia URL");
      return;
    }

    if (!validateUrl(url)) {
      setError("Please enter a valid English Wikipedia URL (en.wikipedia.org)");
      return;
    }

    setLoading(true);

    // todo: remove mock functionality - replace with actual API call
    setTimeout(() => {
      const mockQuiz: QuizData = {
        title: url.split("/wiki/")[1]?.replace(/_/g, " ") || "Sample Article",
        summary:
          "This is a mock quiz generated from the Wikipedia article. In the full application, this will be generated by Gemini AI based on the actual article content.",
        questions: [
          {
            question: "What is the main topic of this article?",
            options: [
              "Option A - Correct answer",
              "Option B",
              "Option C",
              "Option D",
            ],
            correct_answer: 0,
            explanation:
              "This explanation describes why the correct answer is correct and provides additional context from the article.",
          },
          {
            question: "Which of the following is a key concept discussed?",
            options: [
              "Concept 1",
              "Concept 2 - Correct",
              "Concept 3",
              "Concept 4",
            ],
            correct_answer: 1,
            explanation:
              "The article extensively covers this concept in the third section, explaining its importance and applications.",
          },
        ],
        key_entities: ["Entity 1", "Entity 2", "Entity 3", "Entity 4"],
        related_topics: ["Topic A", "Topic B", "Topic C"],
      };

      setQuiz(mockQuiz);
      setLoading(false);
    }, 2000);
  };

  return (
    <div className="space-y-8">
      <div className="text-center py-12">
        <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-primary/10 mb-4">
          <Sparkles className="w-8 h-8 text-primary" />
        </div>
        <h1 className="text-4xl font-bold mb-4">
          Generate AI-Powered Quizzes from Wikipedia
        </h1>
        <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
          Enter any Wikipedia article URL and let AI generate an interactive quiz
          with multiple choice questions, explanations, and key insights.
        </p>
      </div>

      <Card className="max-w-2xl mx-auto">
        <CardContent className="pt-6">
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="wiki-url">Wikipedia Article URL</Label>
              <Input
                id="wiki-url"
                type="text"
                placeholder="https://en.wikipedia.org/wiki/..."
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                disabled={loading}
                className="font-mono text-sm"
                data-testid="input-wiki-url"
              />
              {error && (
                <p className="text-sm text-destructive" data-testid="text-error">
                  {error}
                </p>
              )}
            </div>

            <Button
              type="submit"
              className="w-full"
              disabled={loading}
              data-testid="button-generate-quiz"
            >
              {loading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Generating quiz from Wikipedia article...
                </>
              ) : (
                <>
                  <Sparkles className="mr-2 h-4 w-4" />
                  Generate Quiz
                </>
              )}
            </Button>
          </form>
        </CardContent>
      </Card>

      {quiz && (
        <div className="max-w-4xl mx-auto" data-testid="quiz-display-container">
          <QuizDisplay
            quiz={quiz}
            dateGenerated={new Date().toLocaleDateString("en-US", {
              year: "numeric",
              month: "long",
              day: "numeric",
            })}
          />
        </div>
      )}
    </div>
  );
}
